### ISSUE TITLE
请教一个无法下载bookmark收藏夹的问题

### ISSUE THREAD

**Issue by sd3422524** [leoding86/pixiv-omina#59]
非常感谢您制作了这样的收图工具，它非常棒！
只是在使用途中出现了一些小问题……在我尝试使用“添加任务-收藏夹”的时候会出现这样一个错误而无法进行下载，请问我需要怎样解决呢，谢谢您。

A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Cannot read property 'querySelectorAll' of null
    at IncomingMessage. <anonymous> (C:\Progeam Files (x86)\Pixiv Omina\resources\app.asar\webpack:\src\main\serivces\UserService,js:144:45)
    at IncomingMessage. emit (events.js:205:15)
    at IncomingMessage. EventEmitter.emit (domain.js:471:20)
    at endReeadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)

以上是完整的错误提示，本机的Java版本是：版本 8 更新 281 （工作版本 1.8.0_281-b09）

能否帮忙检查一下具体是什么原因吗？拜谢，期待您的回复

**Comment by leoding86** [comment]
我可以正常下载。问题是一直持续吗？可能是网络问题导致页面没有完整下载导致，也可能是P站现在有什么随机的阻隔措施导致的。需要更多的信息才能继续分析原因。

**Comment by Maynic** [comment]
您好，我也遇到了同样的问题。请问还需要提供哪些信息可以帮助您分析呢？

**Comment by leoding86** [comment]
@Maynic 最近比较忙，没有太关注。目前没有太好的办法分析，因为应用本身没有日志模块，我后续会加入。另外，这个不能下载是持续性的还是断断续续的问题？

**Comment by Maynic** [comment]
> 
> 
> @Maynic 最近比较忙，没有太关注。目前没有太好的办法分析，因为应用本身没有日志模块，我后续会加入。另外，这个不能下载是持续性的还是断断续续的问题？

我的使用频率不是很高，所以不能排除是我每次都碰巧不行。但最近几次的使用都遇到了。
