### ISSUE TITLE
"You don't have permission to write file(s) to that location"

### ISSUE THREAD

**Issue by EagleWingz7500** [leoding86/pixiv-omina#85]
I have a PixivOmina download folder, and usually I will add a sub folder of the Artist's name, but after the update, seems like I can't.
![image](https://user-images.githubusercontent.com/64532647/126075182-539c8fb4-c88b-4dc9-9875-a72d5b9ab8fe.png)

**Comment by leoding86** [comment]
There are 2 reasons for the notification shows up. First, the application can't write configurations to the configuration folder. Second, it can't download file to the target folder.

Run the application as Administrator will resolve most permission issues. But if you don't want to run it using administrator privilege, please check the followings.

1. Make sure you have write permission to the download folder.
2. Make sure you have read and write permission to the installation folder.

You can create any file in the target folder, and you can sure you have the write permission to the folder if there isn't any popup.

**Comment by RSAStudioGames** [comment]
I'm having the same issue even when running it as admin.

**Comment by Mirrorman95** [comment]
I'm also having this problem, even after running it as Administrator.

**Comment by sakkamade** [comment]
@Mirrorman95, Did you run into it when tried to change the "Save to" under "Downloads" tab?

**Comment by Mirrorman95** [comment]
> 
> 
> @Mirrorman95, Did you run into it when tried to change the "Save to" under "Downloads" tab?

Yes.

**Comment by sakkamade** [comment]
Thank you. Could you also share which version it started with?

**Comment by Mirrorman95** [comment]
> 
> 
> Thank you. Could you also share which version it started with?

I've been using version 0.9.1. I don't think I tried much of previous versions, so I don't know if they had the problem, too.

**Comment by sakkamade** [comment]
@Mirrorman95, You can try to find out when it has started (by installing older versions), or use the workaround I mentioned here: https://github.com/leoding86/pixiv-omina/issues/89#issuecomment-901450719

> ... As a temporary workaround I changed the path in the config file.
In my case, the config was in `/home/user/.config/Pixiv Omina/config/settings.config` (I am on Linux).
> Default path can be changed here:
> `{"saveTo":"/default/path", ...}`

> ... (on Windows) search for `settings.config` file or `Pixiv Omina` directory in, e.g. `C:\Users\(username)\AppData\Local` or `C:\Users\(username)\AppData\Roaming`

EDIT: You can also downgrade to version `0.7.7`, as it was the latest stable version I remember.

**Comment by Mirrorman95** [comment]
I

> @Mirrorman95, You can try to find out when it has started (by installing older versions), or use the workaround I mentioned here: [#89 (comment)](https://github.com/leoding86/pixiv-omina/issues/89#issuecomment-901450719)
> 
> > ... As a temporary workaround I changed the path in the config file.
> > In my case, the config was in `/home/user/.config/Pixiv Omina/config/settings.config` (I am on Linux).
> > Default path can be changed here:
> > `{"saveTo":"/default/path", ...}`
> 
> > ... (on Windows) search for `settings.config` file or `Pixiv Omina` directory in, e.g. `C:\Users\(username)\AppData\Local` or `C:\Users\(username)\AppData\Roaming`
> 
> EDIT: You can also downgrade to version `0.7.7`, as it was the latest stable version I remember.

Sorry it took so long to reply. I tried editing that config file manually like you said, but the program changes it back to my computer's default Downloads directory as soon as it boots back up, regardless of whether or not it's being run as an Administrator. I haven't tried downgrading yet, because I can always just move the files afterwards. Would there be any major loss of functionality between the two versions?

**Comment by sakkamade** [comment]
> but the program changes it back to my computer's default Downloads directory

Wow, that's unexpected. In my case, on Linux, it worked. But I also use a several-commits newer version than the 0.9.1 tag, perhaps that is the reason. 
I guess you can try setting the config file as Read-Only?


> Would there be any major loss of functionality between the two versions?

Hm, well, honestly, no, I don't think there would (unless there was a major changes in pixiv api, and 0.7.7 does not work any more). 
Maybe only this one https://github.com/leoding86/pixiv-omina/issues/31#issuecomment-885982838, although I still had no input on whether it was intentional change. 

There was a major refactoring at the time, after 0.7.7—plugins support, etc.—and the work on it quite halted several times already.
I think it is absolutely save to use 0.7.7 until leoding86 will return. 
But please do open new issue reports, if you experience some other problems with the newest version.

**Comment by sakkamade** [comment]
Here user had similar/same problem https://github.com/leoding86/pixiv-omina/issues/89, not sure if they resolved it.

**Comment by 06000208** [comment]
This happens for me on version 0.9.1, windows 10, from the "Add download" modal and the settings menu regardless of whether I run the software regularly or as adminstrator, and I've ensured that the folder's permissions are configured correctly.

Editing the `AppData\Roaming\Pixiv Omina\config\settings.config` file did work and allow me to download to a specific folder.

**Comment by Pinwee** [comment]
> This happens for me on version 0.9.1, windows 10, from the "Add download" modal and the settings menu regardless of whether I run the software regularly or as adminstrator, and I've ensured that the folder's permissions are configured correctly.
> 
> Editing the `AppData\Roaming\Pixiv Omina\config\settings.config` file did work and allow me to download to a specific folder.

Thank you, my friend, through your method, I successfully modified the download address of the file.

**Comment by Mirrorman95** [comment]
> This happens for me on version 0.9.1, windows 10, from the "Add download" modal and the settings menu regardless of whether I run the software regularly or as adminstrator, and I've ensured that the folder's permissions are configured correctly.
> 
> Editing the `AppData\Roaming\Pixiv Omina\config\settings.config` file did work and allow me to download to a specific folder.

Thanks, that fixed it for me, too.

**Comment by ysg-ysg** [comment]
I meet the same problem, and find the error information in a log file in
\AppData\Roaming\Pixiv Omina\app.log
wish it helps to locate the problem

[2025-01-10 19:25:16]Error: You don't have permission to write file(s) to the location
    at C:\Software\Pixiv Omina\resources\app.asar\webpack:\src\main\services\SettingService.js:66:17
    at C:\Software\Pixiv Omina\resources\electron.asar\common\api\deprecate.js:156:56
    at processTicksAndRejections (internal/process/task_queues.js:82:9)

**Comment by JunkCreekG** [comment]
> There are 2 reasons for the notification shows up. First, the application can't write configurations to the configuration folder. Second, it can't download file to the target folder.
> 
> Run the application as Administrator will resolve most permission issues. But if you don't want to run it using administrator privilege, please check the followings.
> 
> 1. Make sure you have write permission to the download folder.
> 2. Make sure you have read and write permission to the installation folder.
> 
> You can create any file in the target folder, and you can sure you have the write permission to the folder if there isn't any popup.

Found the solution finally.

in `C:\Users\[user]\AppData\Roaming\Pixiv Omina\config\settings.config`, change this **_`{"saveTo":"D:\\Downloads`_** to **_`{"saveTo":"D:\\Downloads\\Pixiv`_** for example.

We should use double back slash

**Comment by JunkCreekG** [comment]
> I meet the same problem, and find the error information in a log file in \AppData\Roaming\Pixiv Omina\app.log wish it helps to locate the problem
> 
> [2025-01-10 19:25:16]Error: You don't have permission to write file(s) to the location at C:\Software\Pixiv Omina\resources\app.asar\webpack:\src\main\services\SettingService.js:66:17 at C:\Software\Pixiv Omina\resources\electron.asar\common\api\deprecate.js:156:56 at processTicksAndRejections (internal/process/task_queues.js:82:9)

Found the solution finally.

in `C:\Users\[user]\AppData\Roaming\Pixiv Omina\config\settings.config`, change this **_`{"saveTo":"D:\\Downloads`_** to **_`{"saveTo":"D:\\Downloads\\Pixiv`_** for example.

We should use double back slash
